collections:
  vigilantes:
    output: true
    permalink: /:collection/:name

  mha:
    output: true
    permalink: /:name

  volume:
    output: true
    permalink: /:collection/:name

  s-vigilantes:
    output: true
    permalink: /:collection/:name

  s-mha:
    output: true
    permalink: /s/:name

defaults:
  - scope:
      path: ""
      type: "vigilantes"
    values:
      layout: "manga"
  - scope:
      path: ""
      type: "mha"
    values:
      layout: "s-manga"
  - scope:
      path: ""
      type: "s-vigilantes"
    values:
      layout: "scroll"
  - scope:
      path: ""
      type: "s-mha"
    values:
      layout: "scroll"
  - scope:
      path: ""
    values:
      layout: "default"